### ISSUE TITLE
Compact summary for Grid component

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#1265]
### Description

**Update 05.08.24**
We believe this issue is sufficiently solved with the new designs and concept for Summary 2.0. I have shown examples from the new grid summary to the original reporter and we could agree that the current design works much better. I'm closing this issue as we don't see a current need for a compact grid component in summary.

Currently only groups (i.e. non-repeating groups) show a compact summary by default. This should be possible for Grid as well, possibly if the Grid component is displayed within a (non-repeating) Group.

### Additional Information

- https://altinn.slack.com/archives/C02EVE4RU82/p1687243819934929
```[tasklist]
### Tasks
```

**Comment by CelineTrammi** [comment]
Can org/krt be added as a label to this issue as well? 🙏

**Comment by adamhaeger** [comment]
I've implemented support for compact grid view in this draft PR: https://github.com/Altinn/app-frontend-react/pull/2250

However I cant seem to find design for how the grid summary should look in compact mode, si assigning this to @Edavda for now :)

**Comment by olemartinorg** [comment]
I'm not quite sure this is relevant for `Summary2`? The issue was rooted in old Summary component concepts, and I'd rather wait until we see a need for a more compact variant (or even a less compact variant?) of the Grid component in `Summary2` when those experiences start coming in. I'm in favor of just closing this issue as no longer relevant.

**Comment by Edavda** [comment]
I agree with that approach @olemartinorg. 
Also, I don't quite understand what the specific needs are here. I looked into the Slack thread that is linked, but I still can't understand exactly what the problem is. We should define that clearly before we design an alternate view for the grid component. 

We have a chat scheduled later today around open summary tasks, so we'll look into this issue and figure out how to move forward.
